stages:
  - build

build_job:
  stage: build
  tags:
    - For-Build
  script:
    - echo "Build started...."
    - cd /home/ec2-user/builds/t3_Kxqzci/0/kz1021/veriref/
    - docker build -t veriref-app .
    - docker run -p 5000:5000 veriref-app