default:
  before_script:
    - echo MISTRAL_ENDPOINT="$MISTRAL_ENDPOINT" >> .env

stages:
  - deploy  

deploy:
  image: ubuntu:latest
  stage: deploy    # deploy to heroku
  script:
    - sudo gem install dpl
<<<<<<< HEAD
    - sudo dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_PRODUCTION_KEY
=======
    - sudo dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_PRODUCTION_KEY
>>>>>>> dev
