stages:
  - build
  - test
  - release

build_job:
  stage: build
  tags:
    - For-Build
  script:
    - echo "Build started...."
    - echo $CI_REGISTRY"
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build -t myflaskapp:$CI_PIPELINE_ID .
    - docker tag myflaskapp:$CI_PIPELINE_ID $CI_REGISTRY/harsh005/docker-project/myflaskapp:$CI_PIPELINE_ID
    - docker push $CI_REGISTRY/harsh005/docker-project/myflaskapp:$CI_PIPELINE_ID

deploy_job:
  stage: release
  tags:
    - For-CD
  script:
    - echo "Deploying started...."
    - docker rm -f myapp || true
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker pull $CI_REGISTRY/harsh005/docker-project/myflaskapp:$CI_PIPELINE_ID
    - docker run -dit --name myapp -p 80:8080 $CI_REGISTRY/harsh005/docker-project/myflaskapp:$CI_PIPELINE_ID